[package]
name = "rasp-integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dev-dependencies]
android-apk = { path = "../crates/android-apk" }
android-axml = { path = "../crates/android-axml" }
artifact-inspector = { path = "../crates/artifact-inspector" }
serde_json.workspace = true
zip.workspace = true
